# Generated by Django 5.0.3 on 2024-04-19 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('height', models.IntegerField()),
                ('weight', models.FloatField()),
                ('ap_hi', models.IntegerField()),
                ('ap_lo', models.IntegerField()),
                ('cholesterol', models.IntegerField(choices=[(1, 'Normal'), (2, 'Above Normal'), (3, 'High')])),
                ('gluc', models.IntegerField(choices=[(1, 'Normal'), (2, 'Above Normal'), (3, 'High')])),
                ('smoke', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('alco', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('active', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')])),
                ('prediction_result', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.patient')),
            ],
        ),
    ]
